feedshare/feedlists/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    'feedshare.feedlists.views',

    url(r'^$', 'index', name='feedlists_index'),
    url(r'^share/$', 'share', name='feedlists_share'),
    url(r'^popular/$', 'popular', name='feedlists_popular'),
    url(r'^search/$', 'search', name='feedlists_search'),

    url(r'^autocomplete/tags/$',
        'autocomplete_tags', name='feedlists_autocomplete_tags'),
    url(r'^tags/$',
        'tags', name='feedlists_tags'),
    url(r'^tag/$',
        'tag', name='feedlists_tag'),
    url(r'^tags/(?P<tag>.+)/$',
        'tag', name='feedlists_tag_specific'),

    url(r'^(?P<slug>[0-9A-Za-z\-\_]+)/edit/(?P<secret>[0-9A-Za-z]+)/$',
        'edit', name='feedlists_edit'),
    url(r'^(?P<slug>[0-9A-Za-z\-\_]+)/$',
        'view', name='feedlists_view'),
)

feedshare/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    '',

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^legal/$', TemplateView.as_view(
        template_name='general/legal.html'), name='legal'),
    url(r'^imprint/$', TemplateView.as_view(
        template_name='general/imprint.html'), name='imprint'),
    url(r'^privacy/$', TemplateView.as_view(
        template_name='general/privacy.html'), name='privacy'),
    url(r'^contribute/$', TemplateView.as_view(
        template_name='general/contribute.html'), name='contribute'),
    url(r'^accounts/profile/$', TemplateView.as_view(
        template_name='account/profile.html'), name='profile'),
    (r'^accounts/', include('allauth.urls')),
    url(r'^', include('feedshare.feedlists.urls')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedshare/feedlists/models.py
import os
import re
import uuid
import hashlib
import datetime
import urlparse
import time

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.timezone import now

from taggit.managers import TaggableManager

import listparser

current_milli_time = lambda: int(round(time.time() * 1000))

POPULARITY_HN_GRAVITY = 1.2  # hn: 1.8


def get_upload_path(instance, filename):
    directory = instance.slug \
        or hashlib.md5(str(uuid.uuid4())).hexdigest()[0:10]
    return os.path.join('lists', directory, filename)

remove_email_re = re.compile(r'.*(([_a-z0-9-]+?(\.[_a-z0-9-]+?)*)@' +
                             '([a-z0-9-]+?(\.[a-z0-9-]+?)*(\.[a-z]{2,4}))).*')


def remove_email(string):
    result = remove_email_re.match(string)
    return string.replace('@%s' % result.groups()[3], '') if result else string


class PopularityModel(models.Model):
    datetime_created = models.DateTimeField(auto_now_add=True)
    votes = models.PositiveIntegerField(default=0)

    # http://stackoverflow.com/questions/11128086/simple-popularity-algorithm
    popularity_pt2_a = models.FloatField(default=0)
    popularity_pt2_b = models.FloatField(default=0)

    # http://amix.dk/blog/post/19574
    popularity_hn = models.FloatField(default=0)

    class Meta:
        abstract = True

    def vote(self, t=None):
        self.votes += 1
        if not t:
            t = float(current_milli_time())
        self.update_popularity_pt2_a(t)
        self.update_popularity_pt2_b(t)
        self.update_popularity_hn()

    def update_popularity_pt2_a(self, t):
        p = float(self.popularity_pt2_a)
        self.popularity_pt2_a = (p + t) / 2.0 if p else t

    def update_popularity_pt2_b(self, t):
        p = float(self.popularity_pt2_b)
        if p:
            self.popularity_pt2_b = (p + t) / 2.0
        else:
            initial = self.__class__.objects.aggregate(
                models.Avg('popularity_pt2_b')
            ).values()[0]
            self.popularity_pt2_b = initial if initial > 0 else t

    def update_popularity_hn(self):
        t = float((now() - self.datetime_created).seconds) / 3600
        p = (self.votes - 1) / ((t + 2) ** POPULARITY_HN_GRAVITY)
        self.popularity_hn = p


class FeedList(PopularityModel):
    slug = models.SlugField(
        max_length=255,
        unique=True,
        help_text='Part of the URL (http://feedshare.net/your-slug)')
    title = models.CharField(
        max_length=255,
        blank=True, null=True)
    description = models.TextField(
        blank=True, null=True)
    author = models.CharField(
        max_length=255,
        blank=True, null=True,
        verbose_name='Your name')
    author_email = models.EmailField(
        max_length=255,
        blank=True, null=True,
        verbose_name='E-mail address',
        help_text='Not public, just to recover the secret editing key')
    file = models.FileField(
        upload_to=get_upload_path,
        blank=True, null=True,
        verbose_name='OPML File')
    url = models.URLField(
        max_length=255,
        blank=True, null=True,
        verbose_name='OPML URL')
    secret = models.CharField(
        max_length=255)
    processing_error = models.BooleanField(
        blank=True,
        default=False)
    datetime_process = models.DateTimeField(
        blank=True, null=True)
    datetime_updated = models.DateTimeField(
        blank=True, null=True)
    views = models.PositiveIntegerField(
        default=0)

    feeds = models.ManyToManyField('Feed', through='FeedListFeed')
    tags = TaggableManager()

    class Meta:
        verbose_name = 'Feedlist'
        verbose_name_plural = 'Feedlist'

    def __unicode__(self):
        return remove_email(self.title if self.title else self.slug)

    def save(self, *args, **kwargs):
        if self.title and not len(self.title):
            self.title = None
        if not self.secret:
            self.secret = hashlib.md5(str(uuid.uuid4())).hexdigest()[0:10]
        super(FeedList, self).save(*args, **kwargs)

    def view(self):
        self.update_if_necessary()
        self.views += 1
        self.save()

    def get_absolute_url(self):
        return reverse('feedlists_view', kwargs=dict(
            slug=self.slug))

    def get_edit_url(self):
        return reverse('feedlists_edit', kwargs=dict(
            slug=self.slug,
            secret=self.secret))

    def filename(self):
        if self.file:
            return os.path.basename(self.file.name)

    def url_filename(self):
        if self.url:
            return os.path.basename(self.url)

    def update_if_necessary(self):
        if self.processing_error:
            aged = now() - datetime.timedelta(minutes=5)
            if not self.datetime_process or self.datetime_process < aged:
                self.update_feeds()
        elif self.url:
            aged = now() - datetime.timedelta(days=1)
            if not self.datetime_updated or self.datetime_updated < aged:
                success = self._process_url()
                self.update_success(success, save=False)
        return self.processing_error

    def update_feeds(self):
        success = False
        if self.url:
            success = self._process_url()
        elif self.file:
            success = self._process_file()
        self.update_success(success)
        return success

    def update_success(self, success, save=True):
        self.datetime_process = now()
        if success:
            self.processing_error = False
            self.datetime_updated = now()
        else:
            self.processing_error = True
        if save:
            self.save()
        return not self.processing_error

    def _process_url(self):
        url = str(self.url)
        result = listparser.parse(url)
        if result['bozo'] == 1:
            return False
        self._process_result(result)
        return True

    def _process_file(self):
        result = listparser.parse(self.file, 'feedshare.net')
        if result['bozo'] == 1 and not result['feeds']:
            return False
        self._process_result(result)
        return True

    def _process_result(self, result):
        if not self.pk:
            self.save()
        if (not self.title or not len(self.title)) and result.meta.title:
            self.title = result.meta.title

        feedlistfeed_pks = []

        for feed_data in result.feeds:
            feed, feed_created = Feed.objects\
                .get_or_create(
                    url=feed_data['url'],
                    defaults={'title': feed_data['title']})
            feedlistfeed, feedlistfeed_created = FeedListFeed.objects\
                .get_or_create(feed=feed, feedlist=self)
            if feedlistfeed_created:
                feed.vote()
            feedlistfeed.title = feed_data['title']
            feedlistfeed.tags.add(*[x.lower() for x in feed_data['tags']])
            feedlistfeed.save()
            feedlistfeed_pks.append(feedlistfeed.pk)

        FeedListFeed.objects.filter(feedlist=self)\
            .exclude(pk__in=feedlistfeed_pks)\
            .delete()


class FeedListFeed(models.Model):
    feedlist = models.ForeignKey('FeedList')
    feed = models.ForeignKey('Feed')
    title = models.CharField(max_length=255, blank=True, null=True)
    tags = TaggableManager()

    class Meta:
        verbose_name = 'Feedlist Feed'
        verbose_name_plural = 'Feedlist Feeds'

    def __unicode__(self):
        return unicode(self.title)


class Feed(PopularityModel):
    url = models.TextField()
    site_url = models.URLField(blank=True, null=True)
    title = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = 'Feed'
        verbose_name_plural = 'Feeds'

    def __unicode__(self):
        return unicode(self.url)

    def save(self, *args, **kwargs):
        self.site_url = '{uri.scheme}://{uri.netloc}/'.format(
            uri=urlparse.urlparse(self.url))
        super(Feed, self).save(*args, **kwargs)

feedshare/feedlists/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseForbidden
from django.http import HttpResponseBadRequest
from django.contrib import messages
from django.db.models import Q
from django.db.models import Count
from django.utils import simplejson
from django.views.decorators.cache import cache_page
from django.views.decorators.cache import never_cache
from django.core.cache import get_cache

from taggit.models import Tag

from .models import FeedList
from .models import Feed
from .models import FeedListFeed
from .forms import FeedListUploadForm
from .forms import FeedListLinkForm
from .forms import FeedListEditForm

cache = get_cache('default')


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


@cache_page(60 * 5)
def index(request, *args, **kwargs):
    return render(request, 'feedlists/index.html')


def view(request, *args, **kwargs):
    feedlist = get_object_or_404(FeedList, slug=kwargs.get('slug'))
    ip = get_client_ip(request)
    view_key = 'feedlist-view:%s:%s' % (feedlist.pk, ip)
    if not cache.get(view_key):
        feedlist.view()
        feedlist.vote()
        cache.set(view_key, True)
    return render(request, 'feedlists/view.html', dict(feedlist=feedlist))


@cache_page(60 * 5)
def popular(request, *args, **kwargs):
    popular_feedlists = FeedList.objects.all().order_by('-views')[:10]
    popular_feeds = Feed.objects.all().annotate(
        list_count=Count('feedlistfeed')
    ).order_by('-list_count')[:10]
    popular_tags = FeedListFeed.tags.most_common()[:19]

    return render(request, 'feedlists/popular.html', dict(
        popular_feedlists=popular_feedlists,
        popular_feeds=popular_feeds,
        popular_tags=popular_tags,
    ))


def search(request, *args, **kwargs):
    q = request.GET.get('q')

    cache_key = 'search:%s:response' % q
    response = cache.get(cache_key)
    #if response:
    #    return response

    feedlists = None
    feeds = None

    if q and len(q):
        feedlists = FeedList.objects.filter(Q(
            Q(title__icontains=q) |
            Q(author__icontains=q) |
            Q(author_email__icontains=q) |
            Q(url__icontains=q) |
            Q(file__icontains=q) |
            Q(tags__name__icontains=q) |
            Q(feedlistfeed__tags__name__icontains=q)
        )).distinct().order_by('-views')[:100]
        feeds = Feed.objects.filter(Q(
            Q(title__icontains=q) |
            Q(url__icontains=q) |
            Q(feedlistfeed__tags__name__icontains=q)
        )).distinct()\
            .annotate(list_count=Count('feedlistfeed'))\
            .order_by('-list_count')[:100]

    response = render(request, 'feedlists/search.html', dict(
        q=q,
        feedlists=feedlists,
        feeds=feeds,
    ))
    cache.set(cache_key, response, 60 * 5)
    return response


def tag(request, *args, **kwargs):
    tag = kwargs.get('tag')
    if not tag:
        tag = request.GET.get('tag')

    cache_key = 'tag:%s:response' % tag
    response = cache.get(cache_key+'no')
    if response:
        return response

    feedlists = None
    feeds = None

    if tag and len(tag):
        feedlists = FeedList.objects.filter(Q(
            Q(tags__name__in=[tag]) |
            Q(feedlistfeed__tags__name__in=[tag])
        )).distinct()[0:100]
        feeds = Feed.objects.filter(
            feedlistfeed__tags__name__in=[tag]
        ).distinct()[0:100]

    response = render(request, 'feedlists/tag.html',  dict(
        tag=tag,
        feedlists=feedlists,
        feeds=feeds,
    ))
    cache.set(cache_key, response, 60 * 5)
    return response


@cache_page(60 * 15)
def tags(request, *args, **kwargs):
    tags = FeedListFeed.tags.most_common()
    return render(request, 'feedlists/tags.html', dict(
        tags=tags
    ))


@never_cache
def share(request):
    used_form = 'upload'

    if request.method == 'POST' and request.POST.get('form_type') == 'upload':
        used_form = 'upload'
        upload_form = FeedListUploadForm(request.POST, request.FILES)
        if upload_form.is_valid():
            feedlist = upload_form.save()
            if feedlist.update_feeds():
                messages.success(request,
                                 'Your feed list has been \
                                 imported successfully.')
                return redirect('feedlists_edit',
                                slug=feedlist.slug,
                                secret=feedlist.secret)
            else:
                messages.error(request,
                               'There was an error importing your feeds.')
    else:
        upload_form = FeedListUploadForm()

    if request.method == 'POST' and request.POST.get('form_type') == 'link':
        used_form = 'link'
        link_form = FeedListLinkForm(request.POST)
        if link_form.is_valid():
            feedlist = link_form.save()
            if feedlist.update_feeds():
                messages.success(request,
                                 'Your feed list has been \
                                 imported successfully.')
                return redirect('feedlists_edit',
                                slug=feedlist.slug,
                                secret=feedlist.secret)
            else:
                messages.error(request,
                               'There was an error importing your feeds.')
    else:
        link_form = FeedListLinkForm()

    return render(request, 'feedlists/share.html', dict(
        upload_form=upload_form,
        link_form=link_form,
        used_form=used_form
    ))


@never_cache
def edit(request, *args, **kwargs):
    feedlist = get_object_or_404(FeedList, slug=kwargs.get('slug'))

    secret = kwargs.get('secret')
    if secret != feedlist.secret:
        messages.error(request,
                       'The secret key you provided \
                       is not valid for this feed list.')
        raise Http403

    if request.method == 'POST':
        form = FeedListEditForm(request.POST, request.FILES, instance=feedlist)
        if form.is_valid():
            feedlist.processing_error = False
            feedlist = form.save()
            if feedlist.update_feeds():
                messages.success(request,
                                 'The feed list has been \
                                 updated successfully.')
                form = FeedListEditForm(instance=feedlist)
            else:
                messages.error(request,
                               'There was an error importing your feeds.')
        else:
            messages.warning(request,
                             'There was an error updating your feed list.')
    else:
        form = FeedListEditForm(instance=feedlist)

    return render(request, 'feedlists/edit.html', dict(
        form=form,
        feedlist=feedlist
    ))


def autocomplete_tags(request):
    query = request.GET.get('q', None)
    if request.method != 'GET' or not query:
        return HttpResponseBadRequest()

    cache_key = 'autocomplete_tags:%s:response' % query
    response = cache.get(cache_key)
    if response:
        return response

    try:
        tags = Tag.objects.filter(name__istartswith=query)\
            .values_list('name', flat=True)
    except:
        tags = Tag.objects.language().filter(name__istartswith=query)\
            .values_list('name', flat=True)

    json = simplejson.dumps(list(tags))
    response = HttpResponse(json, mimetype='text/javascript')
    cache.set(cache_key, response, 30)
    return response

feedshare/feedlists/templates/feedlists/discover.html
{% extends "base.html" %}

{% block title %}Discover{% endblock %}

{% block content %}

<div class="row">
	<div class="col-md-4">
		<h1>Popular lists</h1>
		{% for feedlist in popular_feedlists %}
			<hr />
			<p class="lead">
				<a class="oneline" href="{{ feedlist.get_absolute_url }}">
					{% if feedlist.author %}{{ feedlist.author }}{% else %}{{ feedlist.slug }}{% endif %}
				</a><br />
				<small class="oneline">{{ feedlist }}</small>
			</p>
		{% endfor %}
		<hr />
	</div>
	<div class="col-md-4">
		<h1>Popular feeds</h1>
		{% for feed in popular_feeds %}
			<hr />
			<p class="lead">
				<a class="oneline" href="{{ feed.url }}">{{ feed.title }}</a><br />
				<small class="oneline">{{ feed.url }}</small>
			</p>
		{% endfor %}
		<hr />
	</div>
	<div class="col-md-4">
		<h1>Popular tags</h1>
		<hr />
		<p class="lead">
		{% for tag in popular_tags %}
			<a class="label label-default" href="{% url 'feedlists_tag_specific' tag %}">{{ tag }}</a>
		{% endfor %}
		</p>
	</div>
</div>

{% endblock %}

feedshare/feedlists/templates/feedlists/share.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}Upload or link to your list{% endblock %}

{% block javascript %}
<script type="text/javascript" charset="utf-8">
if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
	$('#link-tab a').tab('show');
}
</script>
{% endblock %}

{% block content %}
<div class="text-center">
	<h1>Share your list</h1>
	<p class="lead">
		Upload or link to your OPML feed list below. It will be publicly available.<br />
		The slug will be part of the link to it.
	</p>
</div>

<div class="row">
	<div class="col-md-6 col-md-offset-3 text-center">

		<!-- Nav tabs -->
		<ul class="nav nav-tabs fs-tabs" id="tabs">
			<li id="upload-tab" class="{% if used_form == 'upload' %}active{% endif %}"><a href="#upload" data-toggle="tab">
				<i class="fa fa-upload"></i>
				Upload
			</a></li>
			<li id="link-tab" class="{% if used_form == 'link' %}active{% endif %}"><a href="#link" data-toggle="tab">
				<i class="fa fa-link"></i>
				Link
			</a></li>
		</ul>

		<!-- Tab panes -->
		<div class="tab-content fs-tab-content">
			<div class="tab-pane {% if used_form == 'upload' %}active{% endif %}" id="upload">

				<div class="visible-mobile">
					<div class="well">
						<p class="alert alert-info" style="margin-bottom:5px;">
							Since you are using a mobile device, you cannot upload your OPML file. To do so, please use a desktop browser. 
							You still may link your file, if it's online.
						</p>
						<p style="margin-bottom:0px;">
							<a href="javascript:$('#link-tab a').tab('show');" class="btn btn-block btn-lg btn-primary">Link OPML</a>
						</p>
					</div>
				</div>

				<form action="{% url 'feedlists_share' %}" method="post" class="form visible-desktop" enctype="multipart/form-data">
					<input type="hidden" name="form_type" value="upload" />
					{% csrf_token %}

						{% if upload_form.errors %}
						<div class="alert alert-danger">
							{% if upload_form.slug.errors %}Slug: {{ upload_form.slug.errors.0 }}<br />{% endif %}
							{% if upload_form.file.errors %}File: {{ upload_form.file.errors.0 }}<br />{% endif %}
						</div>
						{% endif %}

						<div class="well">
							<div class="form-group">
								<div class="input-group" style="margin-bottom:10px;">
									<span class="input-group-addon"><nobr><i class="fa fa-globe"></i>&nbsp;feedshare.net/</nobr></span>
									<input class="form-control input-lg text-left" id="id_slug" maxlength="255" name="slug" placeholder="Slug" required="required" title="List slug" type="text" value="{% if upload_form.slug.value %}{{ upload_form.slug.value }}{% endif %}">
								</div>
							</div>
							<div class="form-group">
								<div class="form-control input-lg"><input id="id_file" name="file" placeholder="OPML file" required="required" title="OPML file" type="file" value="{{ upload_form.file.value }}" /></div>
							</div>
							<p class="text-info" style="margin-bottom:0;">Select a valid OPML file, probably generated by your favorite feed reader.</p>
						</div>
						<p><button type="submit" class="btn btn-success btn-lg"><i class="fa fa-upload"></i> Upload</button></p>
				</form>  	
	
			</div>
			<div class="tab-pane {% if used_form == 'link' %}active{% endif %}" id="link">
  
				<form action="{% url 'feedlists_share' %}" method="post" class="form" enctype="multipart/form-data">
					<input type="hidden" name="form_type" value="link" />
					{% csrf_token %}

					{% if link_form.errors %}
					<div class="alert alert-danger">
						{% if link_form.slug.errors %}Slug: {{ link_form.slug.errors.0 }}<br />{% endif %}
						{% if link_form.url.errors %}URL: {{ link_form.url.errors.0 }}<br />{% endif %}
					</div>
					{% endif %}

					<div class="well fs-tab-well">
						<div class="form-group">
							<div class="input-group" style="margin-bottom:10px;">
								<span class="input-group-addon"><nobr><i class="fa fa-globe"></i>&nbsp;feedshare.net/</nobr></span>
								<input class="form-control input-lg text-left" id="id_slug" maxlength="255" name="slug" placeholder="Slug" required="required" title="List slug" type="text" value="{% if link_form.slug.value %}{{ link_form.slug.value }}{% endif %}">
							</div>
						</div>
						<div class="form-group">
							<input class="form-control input-lg text-center" id="id_url" maxlength="255" name="url" placeholder="URL to your OPML file" required="required" title="List URL" type="text" value="{% if link_form.url.value %}{{ link_form.url.value }}{% endif %}">
						</div>
						<p class="text-info" style="margin-bottom:0;">Enter the URL to your OPML file.<br />It's probably provided by your favorite feed reading service.</p>
					</div>
					<p><button type="submit" class="btn btn-success btn-lg"><i class="fa fa-link"></i> Share</button></p>

				</form>
			</div>
			
		</div>
	</div>
</div>

{% endblock %}

feedshare/feedlists/templates/feedlists/view.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}{{ feedlist }}{% if feedlist.author %} by {{ feedlist.author }}{% endif %}{% endblock %}

{% block meta %}
<meta name="robots" content="nofollow" />
{% endblock %}

{% block javascript %}
<script type="text/javascript" charset="utf-8">
jQuery(function($) {
	$('#FeedList').find('input[type=text]').click(function(event){
		$(this).select();
	});
});
</script>
{% endblock %}

{% block content %}

<div class="row">
	<div class="col-sm-6">
		<h1>{{ feedlist }}</h1>
		{% if feedlist.author %}
		<p class="lead">
			{{ feedlist.author }}
		</p>
		{% endif %}
		{% if feedlist.tags.count %}
		<p>
			{% for tag in feedlist.tags.all %}
			<a class="label label-primary" href="{% url 'feedlists_tag_specific' tag %}">{{ tag }}</a>
			{% endfor %}
		</p>
		{% endif %}
	</div>
	<div class="col-sm-6 text-right">
		<br class="hidden-xs" />
		{% if feedlist.url %}
			<a href="{{ feedlist.url }}" class="btn btn-lg btn-warning fs-download-opml-button">
				<i class="fa fa-download"></i> {{ feedlist.url_filename }}
			</a>
		{% else %}{% if feedlist.file %}
			<a href="{{ feedlist.file.url }}" class="btn btn-lg btn-warning fs-download-opml-button">
				<i class="fa fa-download"></i> {{ feedlist.filename }}
			</a>
		{% endif %}{% endif %}
		<br class="visible-xs" />
		<br class="visible-xs" />
	</div>
</div>

<div id="FeedList">
	<hr class="hidden-xs" />
	{% for feedlistfeed in feedlist.feedlistfeed_set.all %}
		{% with feedlistfeed.feed as feed %}
		{% with feedlistfeed.tags.all as tags %}
		<div class="row">
			<div class="col-md-9 col-sm-7 col-xs-12">
				<h4 class="pull-left">
					<a href="{{ feed.site_url }}" class="text-danger" target="_blank">{{ feed.title }}</a>
				</h4>
				<p class="pull-right">
					{% for tag in tags %}
						<a class="label label-info" href="{% url 'feedlists_tag_specific' tag %}">{{ tag }}</a>
					{% endfor %}
				</p>
			</div>
			<div class="col-md-3 col-sm-5 col-xs-12">
				<div class="input-group">
					<input type="text" class="form-control input-sm" value="{{ feed.url }}" />
					<a class="input-group-addon" href="{{ feed.url }}"><i class="fa fa-link"></i></a>
					<a class="input-group-addon" href="javascript:(function(btn){var z=document.createElement('script');document.subtomeBtn=btn;z.src='https://www.subtome.com/load.js';document.body.appendChild(z);})(this)" data-subtome-resource="{{ feed.url }}"><i class="fa fa-star"></i></a>
				</div>
			</div>
		</div>
		<hr />
		{% endwith %}
		{% endwith %}
	{% endfor %}
</div>
<div class="text-center">
	<i class="fa fa-bookmark"></i> {{ feedlist.feeds.count }} Feeds
	&nbsp;&nbsp;&nbsp;
	<i class="fa fa-calendar-o"></i> {{ feedlist.datetime_updated|date:"SHORT_DATETIME_FORMAT" }}
</div>
<br /><br />

<div class="text-center">
	<style type="text/css" media="screen">
		.a2a_default_style a,
		.a2a_default_style .a2a_dd {
			display: inline-block;
			float: none;
		}
	</style>
	<!-- AddToAny BEGIN -->
	<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
	<a class="a2a_dd" href="http://www.addtoany.com/share_save"></a>
	<a class="a2a_button_facebook"></a>
	<a class="a2a_button_twitter"></a>
	<a class="a2a_button_app_net"></a>
	<a class="a2a_button_google_plus"></a>
	<a class="a2a_button_tumblr"></a>
	<a class="a2a_button_evernote"></a>
	<a class="a2a_button_stumbleupon"></a>
	<a class="a2a_button_delicious"></a>
	<a class="a2a_button_flipboard"></a>
	<a class="a2a_button_digg"></a>
	<a class="a2a_button_instapaper"></a>
	<a class="a2a_button_pocket"></a>
	<a class="a2a_button_pinterest"></a>
	<a class="a2a_button_reddit"></a>
	<a class="a2a_button_pinboard"></a>
	<a class="a2a_button_email"></a>
	</div>
	<script type="text/javascript">
	var a2a_config = a2a_config || {};
	a2a_config.linkname = "Shared feed list: {{ feedlist }}";
	a2a_config.linkurl = "http://feedshare.net{{ feedlist.get_absolute_url }}";
	a2a_config.onclick = 1;
	</script>
	<script type="text/javascript" src="//static.addtoany.com/menu/page.js"></script>
	<!-- AddToAny END -->

</div>

{% endblock %}